from: '"swchen.online support" <no-reply@swchen.online>'
subject: Password Reset from swchen.online
content: |
  You receive this mail because there is a password reset request for the account using this email in swchen.online. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://swchen.online/me/passwd/reset/#{token}](https://swchen.online/me/passwd/reset/#{token})

  Thanks,
  swchen.online team
